t[env:diecimilaatmega328]
platform = atmelavr
board = diecimilaatmega328
framework = arduino
monitor_speed = 115200
build_flags = -flto
lib_deps =
    adafruit/Adafruit GFX Library
    https://github.com/cbm80amiga/ST7789_AVR
    arduino-libraries/Ethernet
    arduino-libraries/NTPClient
    PaulStoffregen/Time
    knolleary/PubSubClient